#!/bin/bash


_(){ sed "s/^/    /" <($*); }

if [[ -z $1 ]];then
    echo USAGE: patchavd PATH/TO/ramdisk.img
    echo 
    echo No image specified. Available:
    echo
    _ find ${ANDROID_SDK_ROOT}/system-images -iname ramdisk.img
    echo
    echo Start the AVD with matching image before patching.
    exit -1
fi

cd $(dirname $0)/preinstall/rootAVD
sh rootAVD.sh $1

# echo
# echo [!] Restart the AVD and flash required modules using Magisk.
